language: ruby
cache: bundler
rvm:
- 2.5.0
deploy:
  provider: rubygems
  api_key:
    secure: SBFtbXgV5+1MdWlK42nkGWPeMpZxLtUiZlCZPbNFyrX2u3w+wRCupoTaFh2WnKUUrH9mQTS3XycDCNOENc+OBgr9jRTj3zWg0EW0AdyveMj7+V8Cl0TNY/AewxkCT2snDAH0KhzndNelhAq4eJrIVwNEs2ARqGY45OGQkHp+G40m96Rf1lbj7w3uAZ6A4eAwwCa0ThRvlFj0f+PWO6EcSSXYmRJBTeqrHBvNsuIl1BmaQ/iXFwuRXWp5jwv/N633pwb2c/F/WdPg20ltB2cDFmABPvfOBNyLopfwaNsW7GMZjHSb+FjvKJ13a0ZcSoZQ7je0i0QhPNjOejDxIQqNiwoWny5qczjh/9CpUOxWgfoklcvaDG12EqO692H9fjGDCTl0v8kK0d32aI9g8iPUWJPJ1F6pFBd+6re9zolMoyN1l734vRmVkYdFYk8MMTneos1Xl9yrkN4vF4f2gLeNA1nk7BXpQgHnIMI7g6yLPbm3cs2yzn+mmDs8gqj8+Ee2oCixSLNBA6GqFYQdKTfrNICstsv3KcbmtC1JfgkWSRz1fo8L20ipQn0c8IVlLmrMt4qkj/NDYch/IPjbtQeH/K+jL54oxJvx3g5GLVeEAhlKyezGv8RcgTZGsbLWTwVmZw1U0XgkEOH3b7TyWFB5T67G7onkvixHI26EtD0/Pjw=
  gem: lone-wolf-theme
  on:
    repo: manid2/lone-wolf-theme
